const jimp = require('jimp')
const mask = jimp.read('./assets/mask.png')
const welcomebg = jimp.read('./assets/welcomebg.png')
const avatar = jimp.read('./assets/randomavatar.png')
mask.resize(128, 128)
avatar.resize(128, 128)
avatar.mask(mask)
avatar.write('./output.png', res => {
	console.log('Done!')
})
